## 行列積

以下のような行列A、Bを考えます。

$$
A = \left[
\begin{array}{ccc}
  -1 & 2 & 3 \\
  4 & -5 & 6 \\
  7 & 8 & -9
\end{array}
\right],
B = \left[
\begin{array}{ccc}
  0 & 2 & 1 \\
  0 & 2 & -8 \\
  2 & 9 & -1
\end{array}
\right]
$$

In [1]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

### 【問題1】行列積を手計算する

AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

$$
AB = 
\left[
\begin{array}{ccc}
  (-1)\times0+2\times0+3\times2 & (-1)\times2+2\times2+3\times9 & (-1)\times1+2\times(-8)+3\times(-1) \\
  4\times0+(-5)\times0+6\times2 & 4\times2+(-5)\times2+6\times9 & 4\times1+(-5)\times(-8)+6\times(-1) \\
  7\times0+8\times0+(-9)\times2 & -7\times0+8\times2+(-9)\times9 & 7\times1+8\times(-8)+(-9)\times(-1)
\end{array}
\right]
=\left[
\begin{array}{ccc}
  6 & 29 & -20 \\
  12 & 52 & 38 \\
  -18 & -51 & -48
\end{array}
\right]
$$

### 【問題2】NumPyの関数による計算

この行列積はNumPyの`np.matmul()`や`np.dot()`、または`@`演算子を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

**3種類の違い**

`np.matmul()`と`np.dot()`は3次元以上の配列で挙動が変わります。`@`演算子は`np.matmul()`と同じ働きをします。

今回のような2次元配列の行列積では`np.matmul()`や`@`演算子が公式に推奨されています。
基本`@`を使うことが多い。

In [2]:
c_ndarray_matmul = np.matmul(a_ndarray, b_ndarray)
print("行列積AB np.matmul()の計算結果\n{}".format(c_ndarray_matmul))

c_ndarray_dot = np.dot(a_ndarray, b_ndarray)
print("行列積AB np.dot()の計算結果\n{}".format(c_ndarray_dot))

c_ndarray_at = a_ndarray@b_ndarray
print("行列積AB @の計算結果\n{}".format(c_ndarray_at))

行列積AB np.matmul()の計算結果
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
行列積AB np.dot()の計算結果
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
行列積AB @の計算結果
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 行列積のスクラッチ実装

`np.matmul()`や`np.dot()`、または`@`演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していきましょう。これにより、行列積の計算に対する理解を深めます。ここで考えるのは行列AとBのような次元が2の配列に限定します。

### 【問題3】ある要素の計算を実装

手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

1. 行列Aの(0,0)の要素 $a_{0, 0}$ と行列Bの(0,0)の要素 $b_{0, 0}$ を掛け合わせる
2. 行列Aの(0,1)の要素 $a_{0, 1}$ と行列Bの(1,0)の要素 $a_{1, 0}$ を掛け合わせる
3. 行列Aの(0,2)の要素 $a_{0, 2}$ と行列Bの(2,0)の要素 $a_{2, 0}$ を掛け合わせる
4. それらの値を全て足し合わせる

数式で表すと

$$
\sum^{3}_{k=1}a_{0,k}b_{k,0}
$$

です。

この計算を`np.matmul()`や`np.dot()`、または`@`演算子を使わずに行うコードを書いてください。

Aの0行目とBの0列目を取り出し、NumPyを使いまとめて掛け算した後`sum`メソッドで足し合わせる。

In [12]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

mul00 = (a_ndarray[0]*b_ndarray[:, 0]).sum()
print(a_ndarray[0,:])
print(b_ndarray[:,0])
print(a_ndarray[0]*b_ndarray[:, 0])
print(" Aの0行目とBの0列目：{}".format(mul00))

[-1  2  3]
[0 0 2]
[0 0 6]
 Aの0行目とBの0列目：6


### 【問題4】行列積を行う関数の作成

問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。

計算結果である $3 \times 3$ の行列Cの各要素 $c_{i, j}$ は数式で表すと次のようになります。

$$
c_{i,j} = \sum^{3}_{k=1}a_{i,k}b_{k,j}
$$

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス $i$ や $j$ を1増やすと、次の行や列に移ることができます。

In [17]:
def matrix_product_q4_1(a, b):
    """
    行列積ABを計算する
    Parameters
    ----------------
    a, b : ndarray
        AとBに対応する行列
    Returns
    ----------------
    ndarray
        計算した行列積
    """
    c = np.empty((a.shape[0], b.shape[1]))

    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c[i, j] = (a[i]*b[:, j]).sum()
    return c

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print("計算結果\n{}".format(matrix_product_q4_1(a_ndarray, b_ndarray)))

計算結果
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


（解答例2）

In [18]:
def matrix_product_q4_2(a, b):
    """
    行列積ABを計算する
    Parameters
    ----------------
    a, b : ndarray
        AとBに対応する行列
    Returns
    ----------------
    ndarray
        計算した行列積
    """
    c = np.zeros((a.shape[0], b.shape[1]))
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                c[i, j] += a[i, k]*b[k, j]
    return c

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print("計算結果\n{}".format(matrix_product_q4_2(a_ndarray, b_ndarray)))

計算結果
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


## 行列積が定義されない組み合わせの行列

次に以下のような例を考えます。    

$$ D = \left[
    \begin{array}{ccc}
      -1 & 2 & 3 \\
      4 & -5 & 6
    \end{array}
  \right],
  E- = \left[
    \begin{array}{ccc}
       -9 & 8 & 7 \\
      6 & -5 & 4
    \end{array}
  \right] $$

```py
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
```

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

### 【問題5】計算が定義されない入力を判定する

問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることを`print()`を使い表示するコードを書き加えてください。

`a.shape[1]==b.shape[0]`の場合のみ計算を行い、そうでない場合は不適切であることを説明する。

In [25]:
def matrix_product_q5_1(a, b):
    c = np.empty((a.shape[0], b.shape[1]))

    if a.shape[1] == b.shape[0]:
        c = (a[:, np.newaxis, :]*b.T).sum(axis=2)
        return c
    else:
        print("a.shape[1] != b.shape[0] : {} != {}".format(a.shape[1], b.shape[0]))
        return None
        
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])
print("計算結果\n{}".format(matrix_product_q5_1(d, e)))

a.shape[1] != b.shape[0] : 3 != 2
計算結果
None


（解答例3）

**組み込み例外** を表示させる方法です。

組み込み例外とは、**ValueError** や **IndexError**、 **ZeroDivisionError** など、用意されているエラーの種類のことです。

ここではValueErrorを表示させることにします。次のような意味を持ちます。ざっくり値関係のエラーであればこれが使われることが多いです。

> 演算子や関数が、正しい型だが適切でない値を持つ引数を受け取ったときや、 IndexError のようなより詳細な例外では記述できない状況で送出されます。

どのエラーを選ぶこともできますが、意味が分かりやすいものにするようにしましょう。

[ValueError — Python 3.7.4 ドキュメント](https://docs.python.org/ja/3/library/exceptions.html#ValueError)

[8. エラーと例外 — Python 3.7.4 ドキュメント](https://docs.python.org/ja/3/tutorial/errors.html)

ちょっとコードを書く時には面倒なためあまり適していない方法ですが、自分以外の人も使うモジュールを作りたいという時などは良いでしょう。

In [ ]:
def matrix_product_q5_3(a, b):
    c = np.empty((a.shape[0], b.shape[1]))

    if a.shape[1] != b.shape[0]:
        raise ValueError("a.shape[1] != b.shape[0] : {} != {}".format(a.shape[1], b.shape[0]))
    c = (a[:, np.newaxis, :]*b.T).sum(axis=2)
    return c

d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])
print("計算結果\n{}".format(matrix_product_q5_3(d, e)))

問題4の関数にそのまま行列を入れると、どのようなエラーになるかを確認しておきます。

In [13]:
# エラーになる
print("計算結果\n{}".format(matrix_product_q4_1(d, e)))

NameError: name 'matrix_product_q4_1' is not defined

### 【問題6】転置

片方の行列を転置することで、行列積が計算できるようになります。

`np.transpose()`や`.T`アトリビュートを用いて転置し、行列積を計算してください。

In [28]:
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])

print("計算結果：\n{}".format(d.T@e))
print("計算結果：\n{}".format(d@e.T))

計算結果：
[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
計算結果：
[[ 46  -4]
 [-34  73]]
